# Generated by Django 4.1.1 on 2022-10-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='customer_nedd',
            new_name='customer_need',
        ),
    ]
